### Get random
GET http://localhost:9200/customers/_doc/spammer
### Get random
GET http://localhost:9200/products/_doc/1

### Bulk document
POST http://localhost:9200/_bulk HTTP/1.1
Content-Type: application/json

< C:\Users\IBRA\Desktop\just-do-it\dbms\pzn-elasticsearch-dasar\data\bulkTest.json